name: Content Validation
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  validate-content:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v1
      - name: Set Environment Variables
        run: echo ::set-env name=FONTAWESOME_PRO_TOKEN::${{ secrets.FONTAWESOME_PRO_TOKEN }}
      - name: Install Package Dependencies
        run: yarn install
      - name: Validate books
        run: yarn run validate-books
      - name: Validate authors
        run: yarn run validate-authors
      - name: Validate series
        run: yarn run validate-series
      - name: Compile
        run: yarn build
