name: Content Validation
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v1
      - name: Install Package Dependencies
        run: yarn install
      - name: Validate
        run: yarn run validate
      - name: Compile
        run: yarn build
